FROM node:lts-alpine as build-stage

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN npm install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# build app for production with minification
RUN npm run build

# production stage
#FROM nginx:alpine
#COPY nginx.conf /etc/nginx/nginx.conf
#COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 3000
#CMD ["nginx", "-g", "daemon off;"]
CMD ["npm", "run", "serve"]