GET http://localhost:8080/users

###
GET http://localhost:8080/user/2

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"admin.Password"
}

###
curl -X POST http://localhost:8080/users \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjpbImFkbWluIl0sInN1YiI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcyODM3MTMwOSwiZXhwIjoxNzI4NDA3MzA5fQ.x31VQvAuqW0PgA2bU3rSh3oyogBJBP0SEEEUQ8uZrUI" \
  -H "Content-Type: application/json" \
  -d '{
        "email":"playerEmail@gmail.com",
        "password":"$2a$12$NLiiv7gVsA1ltsI1tux.xuE8kEKfAmIHIkloVXwqxHXArgfiJ1XoK",
        "role":"player",
        "playerDetails":{
          "name": "test",
          "age": 30,
          "peakAge": 30,
          "rank": 100000,
          "elo": 100000.0,
          "peakElo": 100000.0,
          "clayRaw": 100000.0,
          "grassRaw": 100000.0,
          "hardRaw": 100000.0
        }
      }'


###
POST http://localhost:8080/addRandomData
Authorization: Basic testing@gmail.com:password

###
curl -X PUT "http://localhost:8080/user/2" \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjpbImFkbWluIl0sInN1YiI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcyODM2OTcwNCwiZXhwIjoxNzI4NDA1NzA0fQ.Kj8OrOVpX5QGg8NHsX5jRpGF6lcikNLsp4gf-EiCY9U" \
  -H "Content-Type: application/json" \
  -d '{
        "email":"playerEmail@gmail.com",
        "password":"$2a$12$NLiiv7gVsA1ltsI1tux.xuE8kEKfAmIHIkloVXwqxHXArgfiJ1XoK",
        "role":"player",
        "playerDetails":{
          "name": "test2",
          "age": 40,
          "peakAge": 40,
          "rank": 100000,
          "elo": 100000.0,
          "peakElo": 100000.0,
          "clayRaw": 100000.0,
          "grassRaw": 100000.0,
          "hardRaw": 100000.0
        }
      }'


###
DELETE http://localhost:8080/user/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjpbImFkbWluIl0sInN1YiI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcyODM2OTcwNCwiZXhwIjoxNzI4NDA1NzA0fQ.Kj8OrOVpX5QGg8NHsX5jRpGF6lcikNLsp4gf-EiCY9U
